=== Halliburton-Landmark/freehep/org/freehep/tools/project.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- $Id: project.xsd,v 1.2 2002/07/16 17:21:13 duns Exp $ -->
<!-- XML Schema Definition for the Project Status -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <xsd:element name="PROJECT">
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded">
                <xsd:element name="JAR">
                    <xsd:complexType>
                        <xsd:choice minOccurs="0" maxOccurs="unbounded">
                            <xsd:element name="PATTERN">
                                <xsd:complexType>
                                    <xsd:attribute name="NAME" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="PACKAGE">
                                <xsd:complexType>
                                    <xsd:all>
                                        <xsd:element name="DESCRIPTION"/>
                                        <xsd:element name="STATUS"/>
                                    </xsd:all>
                                    <xsd:attribute name="NAME" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                        <xsd:attribute name="NAME" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="NAME" type="xsd:string" use="required"/>
            <xsd:attribute name="VERSION" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Halliburton-Landmark/freehep/api/status.xml
<?xml version="1.0" ?>
<!--Generated by GenerateStatus, DO NOT EDIT.-->
<PROJECT
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" VERSION="current" NAME="freehep"
    xsi:noNamespaceSchemaLocation="project.xsd">
    <!--Jar freehep-aid -->
    <JAR NAME="freehep-aid">
        <PATTERN NAME="org.freehep.aid.*"/>
        <PATTERN NAME="org.freehep.jaco.rtti.*"/>
        <PATTERN NAME="org.freehep.jaco.generator.*"/>
        <PACKAGE NAME="org.freehep.aid">
            <DESCRIPTION>
                AID - Abstract Interface Definition - A Tool to generate language specific
interfaces and classes (Java, C++, ...)&amp;nbsp; from abstract interface definition
source files (.aid).
            </DESCRIPTION>
            <STATUS>
                JavaInterface, JavaClass and CPPHeader stable, JNIHeader and

            </STATUS>
        </PACKAGE>
    </JAR>
    <!--Jar freehep-aidajni -->
    <JAR NAME="freehep-aidajni">
        <PATTERN NAME="hep.aida.jni.*"/>
    </JAR>
    <!--Jar freehep-base -->
    <JAR NAME="freehep-base">
        <PATTERN NAME="org.freehep.jaco"/>
        <PATTERN NAME="org.freehep.preview.*"/>
        <PATTERN NAME="org.freehep.swing.*"/>
        <PATTERN NAME="org.freehep.util.*"/>
        <PATTERN NAME="org.freehep.xml.*"/>
        <PATTERN NAME="org.freehep.application.*"/>
        <PATTERN NAME="org.freehep.record.*"/>
        <PACKAGE NAME="org.freehep.application">
            <DESCRIPTION>
                Application Framework (see &lt;a href="http://java.freehep.org/lib/freehep/doc/application/"&gt;documentation&lt;/a&gt;).
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.jaco">
            <DESCRIPTION>
                JACO - Java Access to C++ Objects, a tool to generate the JNI layer.
            </DESCRIPTION>
            <STATUS>
                Frozen, outside application may be better.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.preview">
            <DESCRIPTION>
                Package for previewing new classes.
            </DESCRIPTION>
            <STATUS>
                Unstable by definition.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.swing">
            <DESCRIPTION>
                Extensions to swing which are not in Sun's swing package.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util">
            <DESCRIPTION>
                Generic utility classes for FreeHEP.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util.commanddispatcher">
            <DESCRIPTION>
                Dispatcher of commands in a complex application.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util.commandline">
            <DESCRIPTION>
                CommandLine parses a command line for parameters and options.
            </DESCRIPTION>
            <STATUS>
                Stable

            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util.images">
            <DESCRIPTION>
                Image handler to (pre-)load images and icons.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util.io">
            <DESCRIPTION>
                Set of Streams, Readers, Writers, Encoders and Decoders.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util.parameterdatabase">
            <DESCRIPTION>
                Parameter Database (in memory) to store and retrieve application wide values of different types.
            </DESCRIPTION>
            <STATUS>
                Stable&lt;/p&gt;

            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.util.template">
            <DESCRIPTION>
                A simple template engine.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.xml.io">
            <DESCRIPTION>
                The XMLIO package is a set of interfaces and classes to save and restore
objects using XML.
            </DESCRIPTION>
            <STATUS>
                Under Development.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.xml.menus">
            <DESCRIPTION>
                Package for building menus in Java using XML setup files.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.xml.util">
            <DESCRIPTION>
                XML Utilities to add in reading and writing XML.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
    </JAR>
    <!--Jar freehep-demo -->
    <JAR NAME="freehep-demo">
        <PATTERN NAME="org.freehep.demo.*"/>
        <PATTERN NAME="org.freehep.graphicsio.test.*"/>
        <PACKAGE NAME="org.freehep.demo.graphics">
            <DESCRIPTION>
                Demo Application to show the export capabilities of the Graphics2D and
GraphicsIO library of FreeHEP.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.demo.iconbrowser">
            <DESCRIPTION>
                Demo Application to browse and explore Icons.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
    </JAR>
    <!--Jar freehep-graphics2d -->
    <JAR NAME="freehep-graphics2d">
        <PATTERN NAME="org.freehep.graphics2d.*"/>
        <PACKAGE NAME="org.freehep.graphics2d">
            <DESCRIPTION>
                Base classes for VectorGraphics, useful to implement different output formats.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphics2d.font">
            <DESCRIPTION>
                Font encoding tables and lookup classes to query the tables.
            </DESCRIPTION>
            <STATUS>
                Stable, but may change a bit for performance reasons.
            </STATUS>
        </PACKAGE>
    </JAR>
    <!--Jar freehep-graphics3d -->
    <JAR NAME="freehep-graphics3d">
        <PATTERN NAME="org.freehep.graphics3d.*"/>
        <PACKAGE NAME="org.freehep.graphics3d">
            <DESCRIPTION>
                Interactive 3D graphics engine which can either use plain Java or OpenGL.
            </DESCRIPTION>
            <STATUS>
                Not Ready.
            </STATUS>
        </PACKAGE>
    </JAR>
    <!--Jar freehep-graphicsio -->
    <JAR NAME="freehep-graphicsio">
        <PATTERN NAME="org.freehep.graphicsio"/>
        <PATTERN NAME="org.freehep.graphicsio.exportchooser.*"/>
        <PATTERN NAME="org.freehep.graphicsio.font.*"/>
        <PATTERN NAME="org.freehep.graphicsio.test.*"/>
        <PATTERN NAME="org.freehep.graphicsio.jpg.*"/>
        <PATTERN NAME="org.freehep.graphicsio.png.*"/>
        <PATTERN NAME="org.freehep.graphicsio.raw.*"/>
        <PATTERN NAME="org.freehep.graphicsio.examples.*"/>
        <PACKAGE NAME="org.freehep.graphicsio.cgm">
            <DESCRIPTION>
                CGM (Computer Graphics Metafile) Output Format.
            </DESCRIPTION>
            <STATUS>
                Frozen, Version 1 CGM tags implemented, but format not good enough to

            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio">
            <DESCRIPTION>
                I/O for different graphics in and output formats.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.emf">
            <DESCRIPTION>
                EMF, Enhanced Meta File, Input and Output Format.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.exportchooser">
            <DESCRIPTION>
                Export dialogs/choosers for GraphicsIO, allowing the user to pick a file and format.
            </DESCRIPTION>
            <STATUS>
                Stable, but option box needs reorganization.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.font.encoding">
            <DESCRIPTION>
                Deprecated, use org.freehep.graphics2d.font&lt;/p&gt;

@status Deprecated.
            </DESCRIPTION>
            <STATUS>
                Deprecated.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.font">
            <DESCRIPTION>
                Utility classes for encoding, including and/or embedding fonts.
            </DESCRIPTION>
            <STATUS>
                Stable&lt;/p&gt;

            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.font.truetype">
            <DESCRIPTION>
                Interface for TrueType Font information, using a Java Font class or read from a TrueType font file.
            </DESCRIPTION>
            <STATUS>
                Stable, but incomplete.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.gif">
            <DESCRIPTION>
                GIF (Graphics Interchange Format) Output Format.
            </DESCRIPTION>
            <STATUS>
                Stable.
            </STATUS>
        </PACKAGE>
        <PACKAGE NAME="org.freehep.graphicsio.jpg">
            <DESCRIPTION>
